# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller
    - dual_arm_controller
    - torso_controller
    - whole_body_controller
    - head_controller
    - left_gripper_controller
    - right_gripper_controller

  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - left_arm_0
      - left_arm_1
      - left_arm_2
      - left_arm_3
      - left_arm_4
      - left_arm_5
      - left_arm_6
    action_ns: follow_joint_trajectory
    default: true
  right_arm_controller:
    type: FollowJointTrajectory
    joints:
      - right_arm_0
      - right_arm_1
      - right_arm_2
      - right_arm_3
      - right_arm_4
      - right_arm_5
      - right_arm_6
    action_ns: follow_joint_trajectory
    default: true
  dual_arm_controller:
    type: FollowJointTrajectory
    joints:
      - left_arm_0
      - left_arm_1
      - left_arm_2
      - left_arm_3
      - left_arm_4
      - left_arm_5
      - left_arm_6
      - right_arm_0
      - right_arm_1
      - right_arm_2
      - right_arm_3
      - right_arm_4
      - right_arm_5
      - right_arm_6
  torso_controller:
    type: FollowJointTrajectory
    joints:
      - torso_0
      - torso_1
      - torso_2
      - torso_3
      - torso_4
      - torso_5
    action_ns: follow_joint_trajectory
    default: true
  whole_body_controller:
    type: FollowJointTrajectory
    joints:
      - torso_0
      - torso_1
      - torso_2
      - torso_3
      - torso_4
      - torso_5
      - head_0
      - head_1
      - left_arm_0
      - left_arm_1
      - left_arm_2
      - left_arm_3
      - left_arm_4
      - left_arm_5
      - left_arm_6
      - gripper_finger_l1
      - gripper_finger_l2
      - right_arm_0
      - right_arm_1
      - right_arm_2
      - right_arm_3
      - right_arm_4
      - right_arm_5
      - right_arm_6
      - gripper_finger_r1
      - gripper_finger_r2
  head_controller:
    type: FollowJointTrajectory
    joints:
      - head_0
      - head_1
    action_ns: follow_joint_trajectory
    default: true
  left_gripper_controller:
    type: FollowJointTrajectory
    joints:
      - gripper_finger_l1
      - gripper_finger_l2
    # action_ns: follow_joint_trajectory
    # default: true
  right_gripper_controller:
    type: FollowJointTrajectory
    joints:
      - gripper_finger_r1
      - gripper_finger_r2
    # action_ns: follow_joint_trajectory
    # default: true